# -*- coding: utf-8 -*-
"""DAA_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jpMgQ8Rki48Cdlcg_Vj4yQ_huBbG0OYD
"""

#Insertion Sort
def insertion(arr):
  for i in range(1,len(arr)):
    key=arr[i]
    j=i-1
    while j>=0 and key<arr[j]:
      arr[j+1]=arr[j]
      j=j-1
    arr[j+1]=key
def printArray(arr):
  for i in range(len(arr)):
    print(arr[i], end=" ")

arr=list(map(int, input().split(' ')))
insertion(arr)
printArray(arr)

#Selection Sort
A=list(map(int, input().split(' ')))
for i in range(len(A)-1):
  min_index=i
  for j in range(i+1, len(A)):
    if A[min_index]>A[j]:
      min_index=j
  A[i], A[min_index]=A[min_index], A[i]
for i in range(len(A)):
  print(A[i], end=" ")

#Bubble Sort
def bubble(arr):
  n=len(arr)
  for i in range(n):
    swapped=False
    for j in range(0,n-i-1):
      if arr[j]>arr[j+1]:
        arr[j], arr[j+1]=arr[j+1], arr[j]
        swapped=True
    if(swapped==False):
      break
arr=list(map(int,input().split(' ')))
bubble(arr)
for i in range(len(arr)):
  print("%d" %arr[i],end=" ")